export const TAG_LOGOS: Record<string, string> = {
	react: "/assets/brand-logos/logo-react.svg",
	"react-native": "/assets/brand-logos/logo-react.svg",
	typescript: "/assets/brand-logos/logo-ts.svg",
	python: "/assets/brand-logos/logo-python.svg",
	fastapi: "/assets/brand-logos/logo-fastapi.svg",
	"next.js": "/assets/brand-logos/logo-nextjs.svg",
	docker: "/assets/brand-logos/logo-docker.svg",
	postgres: "/assets/brand-logos/logo-postgresql.svg",
	mongodb: "/assets/brand-logos/logo-mongodb.svg",
	redis: "/assets/brand-logos/logo-redis.svg",
	tailwind: "/assets/brand-logos/logo-tailwind.svg",
	"node.js": "/assets/brand-logos/logo-nodejs.svg",
	django: "/assets/brand-logos/logo-django.svg",
	42: "/assets/brand-logos/logo-42.svg",
	vllm: "/assets/brand-logos/logo-vllm.svg",
	drizzle: "/assets/brand-logos/logo-drizzle.svg",
	expo: "/assets/brand-logos/logo-expo.svg",
	mistral: "/assets/brand-logos/logo-mistral.svg",
	c: "/assets/brand-logos/logo-c.svg",
	"c++": "/assets/brand-logos/logo-cplusplus.svg",
	electron: "/assets/brand-logos/logo-electron.svg",
	nestjs: "/assets/brand-logos/logo-nestjs.svg",
};
